services:
    logger-dynamodb:
        image: vaindex-base
        container_name: logger-dynamodb
        volumes:
            - ../../source/logger/dynamodb-logger.py:/code/app.py
            - ../../source/logger/config/dynamodb-logger.json:/code/config.json
        networks:
            - redis_network
            - dynamodb_network
networks:
    redis_network:
        name: redis_network
    dynamodb_network:
        name: dynamodb_network

