services:
   calc-btc-1:
        image: vaindex-base
        container_name: calc-btc-1
        restart: unless-stopped
        environment:
            EXCHANGE_LIST: "bitstamp,coinbase,itbit,kraken,lmax"
            INDEX_CHANNEL: "calc_btc_index"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/calculation/tick_by_tick_index.py:/code/app.py
            - .:/code/
        networks:
            - redis_network


   calc-eth-1:
        image: vaindex-base
        container_name: calc-eth-1
        restart: unless-stopped
        environment:
            EXCHANGE_LIST: "bitstamp,coinbase,itbit,kraken,lmax"
            INDEX_CHANNEL: "calc_eth_index"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/calculation/tick_by_tick_index.py:/code/app.py
            - .:/code/
        networks:
            - redis_network



networks:
  redis_network:
    name: redis_network
    external: true

