services:
  mongo:
    image: bitnami/mongodb
    restart: always
    user: 0:0
    environment:
      MONGODB_ROOT_USERNAME: testing
      MONGODB_ROOT_PASSWORD: testing
    ports:
      - '27017:27017'
    volumes:
      - ./data:/bitnami/mongodb
    networks:
      - mongo_network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testing
      ME_CONFIG_MONGODB_ADMINPASSWORD: testing
      ME_CONFIG_MONGODB_URL: mongodb://testing:testing@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_network









    