services:
  redis-va: 
    image: redislabs/redismod
    volumes:
      - ./redis-cache:/data
    ports:
      - '6379:6379' 
    networks:
      - redis_network
  dynamodb-va:
    image: amazon/dynamodb-local
    command: "-jar DynamoDBLocal.jar -dbPath ./data/"
    user: 0:0
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data
    ports:
      - '8000:8000'
    networks:
      - dynamodb_network
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-va:8000"
      AWS_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: "local"
      AWS_SECRET_ACCESS_KEY: "local"
    networks:
      - dynamodb_network
networks:
  dynamodb_network:
    name: dynamodb_network
  redis_network:
    name: redis_network
