services:
   coinbase-1:
        image: vaindex-base
        container_name: coinbase-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-1:
        image: vaindex-base
        container_name: kraken-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-1:
        image: vaindex-base
        container_name: bitstamp-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-1:
        image: vaindex-base
        container_name: itbit-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-1:
        image: vaindex-base
        container_name: lmax-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   cryptodotcom-1:
        image: vaindex-base
        container_name: cryptodotcom-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitfinex-1:
        image: vaindex-base
        container_name: bitfinex-1
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
networks:
  redis_network:
    name: redis_network
    external: true

