version: '2.3'
services:
  vpn-service:
    image: hwdsl2/ipsec-vpn-server:latest
    container_name: vpn-service
    privileged: true
    restart: always
    mem_limit: 64M
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
    ports:
     - "500:500/udp"
     - "4500:4500/udp"
    networks:
      - vpn-service
    environment:
      VPN_IPSEC_PSK: "P@ssw0rd!" #共享的金鑰，自行定義
      VPN_USER: "********"       #使用者的帳號，自行定義
      VPN_PASSWORD: "*****"  #使用者的密碼，自行定義
networks:
  vpn-service:
    name: vpn-service-network
    driver: bridge