services:
   consol-btc-coinbase:
        image: vaindex-base
        container_name: consol-btc-coinbase
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-kraken:
        image: vaindex-base
        container_name: consol-btc-kraken
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-lmax:
        image: vaindex-base
        container_name: consol-btc-lmax
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-bitstamp:
        image: vaindex-base
        container_name: consol-btc-bitstamp
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-itbit:
        image: vaindex-base
        container_name: consol-btc-itbit
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-cryptodotcom:
        image: vaindex-base
        container_name: consol-btc-cryptodotcom
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-bitfinex:
        image: vaindex-base
        container_name: consol-btc-bitfinex
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


networks:
  redis_network:
    name: redis_network
    external: true

