services:
   consol-btc-coinbase:
        image: vaindex-base
        container_name: consol-btc-coinbase
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-coinbase"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-kraken:
        image: vaindex-base
        container_name: consol-btc-kraken
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-kraken"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-lmax:
        image: vaindex-base
        container_name: consol-btc-lmax
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-lmax"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-bitstamp:
        image: vaindex-base
        container_name: consol-btc-bitstamp
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-bitstamp"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-itbit:
        image: vaindex-base
        container_name: consol-btc-itbit
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-itbit"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-cryptodotcom:
        image: vaindex-base
        container_name: consol-btc-cryptodotcom
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-cryptodotcom"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-btc-bitfinex:
        image: vaindex-base
        container_name: consol-btc-bitfinex
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-bitfinex"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-gemini:
        image: vaindex-base
        container_name: consol-btc-gemini
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-gemini"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-independentreserve:
        image: vaindex-base
        container_name: consol-btc-independentreserve
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "independentreserve"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-independentreserve"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-cexio:
        image: vaindex-base
        container_name: consol-btc-cexio
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cexio"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-cexio"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-btc-erisx:
        image: vaindex-base
        container_name: consol-btc-erisx
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "erisx"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "consol-btc-erisx"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

            
networks:
  redis_network:
    name: redis_network
    external: true

