services:
   consol-kraken:
        build: .
        container_name: consol-kraken
        volumes:
            - ./code/capture/consol-kraken.py:/code/app.py
   consol-coinbase:
        build: .
        container_name: consol-coinbase
        volumes:
            - ./code/capture/consol-coinbase.py:/code/app.py
   consol-itbit:
        build: .
        container_name: consol-itbit
        volumes:
            - ./code/capture/consol-itbit.py:/code/app.py
   consol-lmax:
        build: .
        container_name: consol-lmax
        volumes:
            - ./code/capture/consol-lmax.py:/code/app.py
   consol-bitstamp:
        build: .
        container_name: consol-bitstamp
        volumes:
            - ./code/capture/consol-bitstamp.py:/code/app.py
