services:
   redis-va: 
     image: redislabs/redismod
     volumes:
     - ./redis-cache:/data
     ports:
       - '6379:6379' 
   dynamodb-va:
      image: amazon/dynamodb-local
      ports:
        - '8000:8000'
   dynamodb-admin:
      image: aaronshaf/dynamodb-admin
      network_mode: host  