services:
   coinbase-2:
        image: vaindex-base
        container_name: coinbase-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   kraken-2:
        image: vaindex-base
        container_name: kraken-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/kraken.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   bitstamp-2:
        image: vaindex-base
        container_name: bitstamp-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   itbit-2:
        image: vaindex-base
        container_name: itbit-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/itbit.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   lmax-2:
        image: vaindex-base
        container_name: lmax-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/lmax.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   cryptodotcom-2:
        image: vaindex-base
        container_name: cryptodotcom-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
   bitfinex-2:
        image: vaindex-base
        container_name: bitfinex-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - infra_default
networks:
  infra_default:
    name: infra_default

