services:
   coinbase-2:
        image: vaindex-base
        container_name: coinbase-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-2:
        image: vaindex-base
        container_name: kraken-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-2:
        image: vaindex-base
        container_name: bitstamp-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-2:
        image: vaindex-base
        container_name: itbit-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-2:
        image: vaindex-base
        container_name: lmax-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   cryptodotcom-2:
        image: vaindex-base
        container_name: cryptodotcom-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitfinex-2:
        image: vaindex-base
        container_name: bitfinex-2
        restart: unless-stopped
        volumes:
            - ../../source/capture/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
networks:
  redis_network:
    name: redis_network

