services:
   bus-eta:
        image: vaindex-base
        container_name: bus-eta
        restart: unless-stopped
        ports:
            - '5009:5009'
        environment:
            LISTENING_PORT: 5009
            TS: Asia/Hong_Kong
        volumes:
            - ../source/transport.py:/code/app.py
            - .:/code/
        