services:
   redis-va: 
     image: redislabs/redismod
     volumes:
     - ./redis-cache:/data
     ports:
       - '6379:6379' 
   dynamodb-va:
      image: amazon/dynamodb-local
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
      ports:
        - '8000:8000'
      volumes:
        - "./dynamodb-data:/home/dynamodblocal/data"
      working_dir: /home/dynamodblocal
   dynamodb-admin:
      image: aaronshaf/dynamodb-admin
      enviornment:
        DYNAMO_ENDPOINT: "http://dynamodb-va:8000"
      ports:
        - '8001:8001'
 