services:
   v2ray:
        image: v2fly/v2fly-core
        container_name: v2ray
        restart: unless-stopped
        ports:
                - '9090:9090'
        environment:
            TZ: Asia/Hong_Kong
            V2RAY_VMESS_AEAD_FORCED: false
        command: run -c /etc/v2ray/config.json 
        volumes:
            - ./config/config.json:/etc/v2ray/config.json
            - ./log/access.log:/var/log/v2ray/access.log
            - ./log/error.log:/var/log/v2ray/error.log
        
