services:
  ccdata-wss-6:
        image: vaindex-base
        container_name: ccdata-wss-6
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "CCDATA"
            END_POINT: "wss://client-axfioiyn06.ccdata.io"
            PROD_ID_1: "HKBTCI-USD"
            PROD_ID_2: "HKETHI-USD"
            PROD_ID_3: "HKEXBRR-USD"
            PROD_ID_4: "HKEXERR-USD"
            CRYPTO_ASSET: "CCHKEX"
            APIKEY: "1e0f131269d411f25453ad0820d526e937df1a7c1a929ee46f8b2fbf8cd2d387"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "ccdata-wss-6"
        volumes:
            - ../../source/websocket/ccdata.py:/code/app.py
            - .:/code/
