services:
   consol-eth-coinbase:
        image: vaindex-base
        container_name: consol-eth-coinbase
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-eth-kraken:
        image: vaindex-base
        container_name: consol-eth-kraken
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-eth-lmax:
        image: vaindex-base
        container_name: consol-eth-lmax
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-eth-bitstamp:
        image: vaindex-base
        container_name: consol-eth-bitstamp
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-eth-itbit:
        image: vaindex-base
        container_name: consol-eth-itbit
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-eth-cryptodotcom:
        image: vaindex-base
        container_name: consol-eth-cryptodotcom
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


   consol-eth-bitfinex:
        image: vaindex-base
        container_name: consol-eth-bitfinex
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network

   consol-eth-gemini:
        image: vaindex-base
        container_name: consol-eth-gemini
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/consol/consol.py:/code/app.py
            - ./data/:/code/data/
        networks:
            - redis_network


networks:
  redis_network:
    name: redis_network
    external: true

