services:
   coinbase-eth-rest:
        image: vaindex-base
        container_name: coinbase-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            PROD_ID: "ETH-USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "coinbase-eth-rest"
        volumes:
            - ../../source/rest/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-eth-rest:
        image: vaindex-base
        container_name: kraken-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            PROD_ID: "ETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "kraken-eth-rest"
        volumes:
            - ../../source/rest/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-eth-rest:
        image: vaindex-base
        container_name: bitstamp-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            PROD_ID: "ethusd"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitstamp-eth-rest"
        volumes:
            - ../../source/rest/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-eth-rest:
        image: vaindex-base
        container_name: itbit-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            PROD_ID: "ETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "itbit-eth-rest"
        volumes:
            - ../../source/rest/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-eth-rest:
        image: vaindex-base
        container_name: lmax-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            PROD_ID: "eth-usd"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "lmax-eth-rest"
        volumes:
            - ../../source/rest/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitfinex-eth-rest:
        image: vaindex-base
        container_name: bitfinex-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            PROD_ID: "tETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitfinex-eth-rest"
        volumes:
            - ../../source/rest/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   cryptodotcom-eth-rest:
        image: vaindex-base
        container_name: cryptodotcom-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            PROD_ID: "ETH_USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cryptodotcom-eth-rest"
        volumes:
            - ../../source/rest/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   gemini-eth-rest:
        image: vaindex-base
        container_name: gemini-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            PROD_ID: "ETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "gemini-eth-rest"
        volumes:
            - ../../source/rest/gemini.py:/code/app.py
            - .:/code/
        networks:
            - redis_network


   cexio-eth-rest:
        image: vaindex-base
        container_name: cexio-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cexio"
            PROD_ID: "ETH"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cexio-eth-rest"
        volumes:
            - ../../source/rest/cexio.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   independentreserve-eth-rest:
        image: vaindex-base
        container_name: independentreserve-eth-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "independentreserve"
            PROD_ID: "eth"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "independentreserve-eth-rest"
        volumes:
            - ../../source/rest/independentreserve.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

networks:
  redis_network:
    name: redis_network
    external: true

