services:
  nginx-app:
    image: nginx:1.19.2-alpine
    volumes:
      - ./nginx.conf /etc/nginx/conf.d/default.conf
      - ./localhost.crt /etc/nginx/nginx/files/localhost.crt
    ports:
      - '80:80/tcp'
    environment:
      TZ: "Asia/Hong_Kong"
