services:
   coinbase-btc-2:
        image: vaindex-base
        container_name: coinbase-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            PROD_ID: "BTC-USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "coinbase-btc-2"
        volumes:
            - ../../source/websocket/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-btc-2:
        image: vaindex-base
        container_name: kraken-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            PROD_ID: "BTC/USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "kraken-btc-2"
        volumes:
            - ../../source/websocket/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-btc-2:
        image: vaindex-base
        container_name: bitstamp-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            PROD_ID: "live_trades_btcusd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitstamp-btc-2"
        volumes:
            - ../../source/websocket/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-btc-2:
        image: vaindex-base
        container_name: itbit-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            PROD_ID: "BTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "itbit-btc-2"
        volumes:
            - ../../source/websocket/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-btc-2:
        image: vaindex-base
        container_name: lmax-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            PROD_ID: "btc-usd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "lmax-btc-2"
        volumes:
            - ../../source/websocket/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   cryptodotcom-btc-2:
        image: vaindex-base
        container_name: cryptodotcom-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            PROD_ID: "trade.BTC_USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cryptodotcom-btc-2"
        volumes:
            - ../../source/websocket/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitfinex-btc-2:
        image: vaindex-base
        container_name: bitfinex-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            PROD_ID: "tBTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitfinex-btc-2"
        volumes:
            - ../../source/websocket/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   gemini-btc-2:
        image: vaindex-base
        container_name: gemini-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            PROD_ID: "BTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "gemini-btc-2"
        volumes:
            - ../../source/websocket/gemini.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   independentreserve-btc-2:
        image: vaindex-base
        container_name: independentreserve-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "independentreserve"
            PROD_ID: "ticker-xbt"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "independentreserve-btc-2"
        volumes:
            - ../../source/websocket/independentreserve.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   erisx-btc-2:
        image: vaindex-base
        container_name: erisx-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "erisx"
            PROD_ID: "BTC/USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "erisx-btc-2"
        volumes:
            - ../../source/websocket/erisx.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   cexio-btc-2:
        image: vaindex-base
        container_name: cexio-btc-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cexio"
            PROD_ID: "BTC-USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cexio-btc-2"
        volumes:
            - ../../source/websocket/cexio.py:/code/app.py
            - .:/code/
        networks:
            - redis_network


networks:
  redis_network:
    name: redis_network
    external: true

