services:
   coinbase-btc-rest:
        image: vaindex-base
        container_name: coinbase-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            PROD_ID: "BTC-USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "coinbase-btc-rest"
        volumes:
            - ../../source/rest/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
            
   kraken-btc-rest:
        image: vaindex-base
        container_name: kraken-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            PROD_ID: "XBTUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "kraken-btc-rest"
        volumes:
            - ../../source/rest/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   bitstamp-btc-rest:
        image: vaindex-base
        container_name: bitstamp-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            PROD_ID: "btcusd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitstamp-btc-rest"
        volumes:
            - ../../source/rest/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   itbit-btc-rest:
        image: vaindex-base
        container_name: itbit-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            PROD_ID: "BTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "itbit-btc-rest"
        volumes:
            - ../../source/rest/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   lmax-btc-rest:
        image: vaindex-base
        container_name: lmax-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            PROD_ID: "btc-usd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "lmax-btc-rest"
        volumes:
            - ../../source/rest/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   bitfinex-btc-rest:
        image: vaindex-base
        container_name: bitfinex-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            PROD_ID: "tBTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "bitfinex-btc-rest"
        volumes:
            - ../../source/rest/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   cryptodotcom-btc-rest:
        image: vaindex-base
        container_name: cryptodotcom-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            PROD_ID: "BTC_USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cryptodotcom-btc-rest"
        volumes:
            - ../../source/rest/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   gemini-btc-rest:
        image: vaindex-base
        container_name: gemini-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            PROD_ID: "BTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "gemini-btc-rest"
        volumes:
            - ../../source/rest/gemini.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   cexio-btc-rest:
        image: vaindex-base
        container_name: cexio-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cexio"
            PROD_ID: "BTC"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "cexio-btc-rest"
        volumes:
            - ../../source/rest/cexio.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   independentreserve-btc-rest:
        image: vaindex-base
        container_name: independentreserve-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "independentreserve"
            PROD_ID: "xbt"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
            APP_NAME: "independentreserve-btc-rest"
        volumes:
            - ../../source/rest/independentreserve.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

            
networks:
  redis_network:
    name: redis_network
    external: true

