services:
   coinbase-btc-rest:
        image: vaindex-base
        container_name: coinbase-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            PROD_ID: "BTC-USD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/rest/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-btc-rest:
        image: vaindex-base
        container_name: kraken-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            PROD_ID: "XBTUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/rest/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-btc-rest:
        image: vaindex-base
        container_name: bitstamp-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            PROD_ID: "btcusd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/rest/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-btc-rest:
        image: vaindex-base
        container_name: itbit-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            PROD_ID: "BTCUSD"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/rest/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-btc-rest:
        image: vaindex-base
        container_name: lmax-btc-rest
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            PROD_ID: "BTC-usd"
            CRYPTO_ASSET: "BTC"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/rest/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
networks:
  redis_network:
    name: redis_network
    external: true

