services:
   coinbase-eth-2:
        image: vaindex-base
        container_name: coinbase-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "coinbase"
            PROD_ID: "ETH-USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/coinbase.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   kraken-eth-2:
        image: vaindex-base
        container_name: kraken-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "kraken"
            PROD_ID: "ETH/USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/kraken.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitstamp-eth-2:
        image: vaindex-base
        container_name: bitstamp-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitstamp"
            PROD_ID: "live_trades_ethusd"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/bitstamp.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   itbit-eth-2:
        image: vaindex-base
        container_name: itbit-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "itbit"
            PROD_ID: "ETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/itbit.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   lmax-eth-2:
        image: vaindex-base
        container_name: lmax-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "lmax"
            PROD_ID: "eth-usd"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/lmax.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   cryptodotcom-eth-2:
        image: vaindex-base
        container_name: cryptodotcom-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cryptodotcom"
            PROD_ID: "trade.ETH_USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/cryptodotcom.py:/code/app.py
            - .:/code/
        networks:
            - redis_network
   bitfinex-eth-2:
        image: vaindex-base
        container_name: bitfinex-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "bitfinex"
            PROD_ID: "tETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/bitfinex.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   gemini-eth-2:
        image: vaindex-base
        container_name: gemini-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "gemini"
            PROD_ID: "ETHUSD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/gemini.py:/code/app.py
            - .:/code/
        networks:
            - redis_network



   independentreserve-eth-2:
        image: vaindex-base
        container_name: independentreserve-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "independentreserve"
            PROD_ID: "ticker-eth"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/independentreserve.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   erisx-eth-2:
        image: vaindex-base
        container_name: erisx-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "erisx"
            PROD_ID: "ETH/USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/erisx.py:/code/app.py
            - .:/code/
        networks:
            - redis_network

   cexio-eth-2:
        image: vaindex-base
        container_name: cexio-eth-2
        restart: unless-stopped
        environment:
            EXCHANGE_NAME: "cexio"
            PROD_ID: "ETH-USD"
            CRYPTO_ASSET: "ETH"
            REDIS_HOST: "redis-va"
            REDIS_PORT: "6379"
        volumes:
            - ../../source/websocket/cexio.py:/code/app.py
            - .:/code/
        networks:
            - redis_network


networks:
  redis_network:
    name: redis_network
    external: true

